"""Add EWS module models and extend Area

Revision ID: b318ddfa379d
Revises: 7935dbf48038
Create Date: 2026-02-01 03:46:26.958393

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b318ddfa379d"
down_revision: Union[str, Sequence[str], None] = "7935dbf48038"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analytics_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("area_id", sa.Integer(), nullable=False),
        sa.Column("stability_index", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("soil_moisture_avg", sa.Float(), nullable=True),
        sa.Column("displacement_trend_mm_per_month", sa.Float(), nullable=True),
        sa.Column("rainfall_accumulation_mm", sa.Float(), nullable=True),
        sa.Column("time_range_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("time_range_to", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["area_id"],
            ["areas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analytics_history_area_id"),
        "analytics_history",
        ["area_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytics_history_created_at"),
        "analytics_history",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytics_history_id"), "analytics_history", ["id"], unique=False
    )
    op.create_table(
        "prediction_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("area_id", sa.Integer(), nullable=False),
        sa.Column("hazard", sa.String(), nullable=False),
        sa.Column("horizon", sa.String(), nullable=False),
        sa.Column("risk_score", sa.Float(), nullable=False),
        sa.Column("risk_level", sa.String(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("expected_window_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expected_window_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["area_id"],
            ["areas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prediction_history_area_id"),
        "prediction_history",
        ["area_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prediction_history_created_at"),
        "prediction_history",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prediction_history_id"), "prediction_history", ["id"], unique=False
    )
    op.add_column("areas", sa.Column("monitored_hazards", sa.String(), nullable=True))
    op.add_column("areas", sa.Column("monitoring_status", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("areas", "monitoring_status")
    op.drop_column("areas", "monitored_hazards")
    op.drop_index(op.f("ix_prediction_history_id"), table_name="prediction_history")
    op.drop_index(
        op.f("ix_prediction_history_created_at"), table_name="prediction_history"
    )
    op.drop_index(
        op.f("ix_prediction_history_area_id"), table_name="prediction_history"
    )
    op.drop_table("prediction_history")
    op.drop_index(op.f("ix_analytics_history_id"), table_name="analytics_history")
    op.drop_index(
        op.f("ix_analytics_history_created_at"), table_name="analytics_history"
    )
    op.drop_index(op.f("ix_analytics_history_area_id"), table_name="analytics_history")
    op.drop_table("analytics_history")
    # ### end Alembic commands ###
